<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="20060" started-at="2019-08-27T05:44:50Z" finished-at="2019-08-27T05:45:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="20060" started-at="2019-08-27T05:44:50Z" finished-at="2019-08-27T05:45:10Z">
      <class name="com.training.sanity.tests.pwdrecover">
        <test-method status="PASS" signature="setUpBeforeClass()[pri:0, instance:com.training.sanity.tests.pwdrecover@4501b7af]" name="setUpBeforeClass" is-config="true" duration-ms="12" started-at="2019-08-27T11:14:50Z" finished-at="2019-08-27T11:14:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.sanity.tests.pwdrecover@4501b7af]" name="setUp" is-config="true" duration-ms="8985" started-at="2019-08-27T11:14:50Z" finished-at="2019-08-27T11:14:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validLoginTest()[pri:0, instance:com.training.sanity.tests.pwdrecover@4501b7af]" name="validLoginTest" duration-ms="10023" started-at="2019-08-27T11:14:59Z" finished-at="2019-08-27T11:15:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [GMAIL] but found [e Learning - My education]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [GMAIL] but found [e Learning - My education]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.training.sanity.tests.pwdrecover.validLoginTest(pwdrecover.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLoginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.training.sanity.tests.pwdrecover@4501b7af]" name="tearDown" is-config="true" duration-ms="1000" started-at="2019-08-27T11:15:09Z" finished-at="2019-08-27T11:15:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.training.sanity.tests.pwdrecover -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
